DROP TABLE IF EXISTS `task`;
CREATE TABLE `task`(
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    detail VARCHAR(1000) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(id)
);